// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAOdXoelycwEYdPlxae8nDQGOIKpbjHDFo",
      authDomain: "tiffinito-44c4f.firebaseapp.com",
      databaseURL: "https://tiffinito-44c4f-default-rtdb.firebaseio.com",
      projectId: "tiffinito-44c4f",
      storageBucket: "tiffinito-44c4f.appspot.com",
      messagingSenderId: "321978035171",
      appId: "1:321978035171:web:c3712c52cc830aa5874ed6",
      measurementId: "G-D20ZHPGKVD");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_JUFrwrgUMTVeSIKap-eVzZvGM6rlSo',
    appId: '1:321978035171:android:efa36720b2df700e874ed6',
    messagingSenderId: '321978035171',
    projectId: 'tiffinito-44c4f',
    storageBucket: 'tiffinito-44c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdyLz5SgCGLiIoRQMDz_Zu8olvKeBro4',
    appId: '1:321978035171:ios:db13579fbb70409e874ed6',
    messagingSenderId: '321978035171',
    projectId: 'tiffinito-44c4f',
    storageBucket: 'tiffinito-44c4f.appspot.com',
    iosClientId:
        '321978035171-htp09g1n6q939tctg383olssdqf2qqrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.languagechanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdyLz5SgCGLiIoRQMDz_Zu8olvKeBro4',
    appId: '1:321978035171:ios:db13579fbb70409e874ed6',
    messagingSenderId: '321978035171',
    projectId: 'tiffinito-44c4f',
    storageBucket: 'tiffinito-44c4f.appspot.com',
    iosClientId:
        '321978035171-htp09g1n6q939tctg383olssdqf2qqrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.languagechanger',
  );
}
